export const metadata = {
  title: 'Keluarin Pemium',
  description: 'Generated by H-87',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
